//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbqn.T115OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consult
    {
        public int Id { get; set; }
        public int SourceId { get; set; }
        public string remark { get; set; }
        public short DelFlag { get; set; }
        public int SubBy { get; set; }
        public System.DateTime subTiem { get; set; }
        public string stuName { get; set; }
        public string sex { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string major { get; set; }
        public string industry { get; set; }
        public string basis { get; set; }
        public string FavoriteIndusery { get; set; }
        public string FavoriteJob { get; set; }
        public string CurrentSchool { get; set; }
        public string grade { get; set; }
        public bool hope { get; set; }
        public int DepartmentId { get; set; }
        public string Statedoor { get; set; }
        public string referrer { get; set; }
    
        public virtual education education { get; set; }
        public virtual Source Source { get; set; }
        public virtual Department Department { get; set; }
    }
}
