//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbqn.T115OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultInfo
    {
        public int Id { get; set; }
        public int StudentResult { get; set; }
        public System.DateTime subTiem { get; set; }
        public int SubjectId { get; set; }
        public int StudentFileId { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual StudentFile StudentFile { get; set; }
    }
}
