//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbqn.T115OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Role = new HashSet<Role>();
            this.ActionInfo = new HashSet<ActionInfo>();
            this.SalaryInfo = new HashSet<SalaryInfo>();
            this.AttendanceInfo = new HashSet<AttendanceInfo>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public string Telphone { get; set; }
        public int State { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public string Remark { get; set; }
        public int DepartmentId { get; set; }
        public string Identification { get; set; }
        public string Address { get; set; }
        public int PostInfoId { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<ActionInfo> ActionInfo { get; set; }
        public virtual ICollection<SalaryInfo> SalaryInfo { get; set; }
        public virtual PostInfo PostInfo { get; set; }
        public virtual ICollection<AttendanceInfo> AttendanceInfo { get; set; }
    }
}
